from typing import List
import uuid

from .schema import PPTDraft, PPTSection
from pptx.enum.text import PP_ALIGN
from .presenton_core.models.pptx_models import (
    PptxPresentationModel,
    PptxSlideModel,
    PptxTextBoxModel,
    PptxPositionModel,
    PptxParagraphModel,
    PptxFontModel,
    PptxSpacingModel,
    PptxTextRunModel,
    PptxFillModel,
)

def map_draft_to_pptx_model(draft: PPTDraft) -> PptxPresentationModel:
    slides: List[PptxSlideModel] = []
    
    # --- Title Slide ---
    title_slide = PptxSlideModel(
        shapes=[
            PptxTextBoxModel(
                position=PptxPositionModel(left=100, top=200, width=1080, height=150),
                paragraphs=[
                    PptxParagraphModel(
                        text=draft.title,
                        font=PptxFontModel(
                            size=60, 
                            font_weight=700, 
                            name="Arial", 
                            color="000000"
                        ),
                        alignment=PP_ALIGN.CENTER
                    )
                ],
                text_wrap=True
            ),
            PptxTextBoxModel(
                position=PptxPositionModel(left=100, top=400, width=1080, height=50),
                paragraphs=[
                    PptxParagraphModel(
                        text="Generated by Spark2Scale AI",
                        font=PptxFontModel(
                            size=24, 
                            name="Arial", 
                            color="666666"
                        ),
                        alignment=PP_ALIGN.CENTER
                    )
                ]
            )
        ]
    )
    slides.append(title_slide)
    
    # --- Content Slides ---
    for section in draft.sections:
        shapes = []
        
        # Slide Title
        shapes.append(
            PptxTextBoxModel(
                position=PptxPositionModel(left=50, top=40, width=1180, height=80),
                paragraphs=[
                    PptxParagraphModel(
                        text=section.title,
                        font=PptxFontModel(
                            size=40, 
                            font_weight=700, 
                            name="Arial", 
                            color="000000"
                        )
                    )
                ]
            )
        )
        
        # Slide Content (Bullets)
        content_paragraphs = []
        for bullet in section.content:
            content_paragraphs.append(
                PptxParagraphModel(
                    text="• " + bullet,  # Simple bullet simulation
                    font=PptxFontModel(size=24, name="Arial"),
                    spacing=PptxSpacingModel(bottom=10)
                )
            )
            
        shapes.append(
            PptxTextBoxModel(
                position=PptxPositionModel(left=50, top=140, width=1180, height=500),
                paragraphs=content_paragraphs,
                text_wrap=True
            )
        )
        
        slide = PptxSlideModel(
            shapes=shapes,
            note=section.speaker_notes
        )
        slides.append(slide)
        
    return PptxPresentationModel(
        name=draft.title,
        slides=slides
    )
